# Generated by Django 2.2.3 on 2019-07-07 14:57

import ORM.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0002_auto_20190707_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=ORM.models.Teacher, on_delete=django.db.models.deletion.CASCADE, to='ORM.Teacher', verbose_name='课程教师'),
            preserve_default=ORM.models.Teacher,
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(to='ORM.Course', verbose_name='课程'),
        ),
        migrations.CreateModel(
            name='TeacherAssistant',
            fields=[
                ('nickname', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False, verbose_name='昵称')),
                ('hobby', models.CharField(blank=True, max_length=100, null=True, verbose_name='爱好')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORM.Teacher', verbose_name='讲师')),
            ],
            options={
                'verbose_name': '助教信息表',
                'verbose_name_plural': '助教信息表',
                'db_table': 'course_assistant',
            },
        ),
    ]
