# Generated by Django 2.2.3 on 2019-07-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0004_auto_20190707_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('1', '男'), ('2', '女'), ('0', '保密')], default='0', max_length=1, verbose_name='性别'),
        ),
    ]
